apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/awslabs/kubernetes-iteration-toolkit/tree/main/operator/config/controller/deployment.yaml
  - https://github.com/awslabs/kubernetes-iteration-toolkit/tree/main/operator/config/controller/rbac.yaml
  - https://github.com/awslabs/kubernetes-iteration-toolkit/tree/main/operator/config/control-plane-crd.yaml
  - https://github.com/awslabs/kubernetes-iteration-toolkit/tree/main/operator/config/webhook/deployment.yaml
  - https://github.com/awslabs/kubernetes-iteration-toolkit/tree/main/operator/config/webhook/rbac.yaml
  - https://github.com/awslabs/kubernetes-iteration-toolkit/tree/main/operator/config/webhook/secret.yaml
  - https://github.com/awslabs/kubernetes-iteration-toolkit/tree/main/operator/config/webhook/service.yaml
  - https://github.com/awslabs/kubernetes-iteration-toolkit/tree/main/operator/config/webhook/webhook.yaml
