apiVersion: v1
kind: ServiceAccount
metadata:
  name: kit-webhook
  namespace: kit
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kit-webhook
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kit-webhook
subjects:
- kind: ServiceAccount
  name: kit-webhook
  namespace: kit
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kit-webhook
  namespace: kit
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kit-webhook
subjects:
- kind: ServiceAccount
  name: kit-webhook
  namespace: kit
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kit-webhook
  namespace: kit
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
  - update
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - watch
  - create
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kit-webhook
rules:
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - validatingwebhookconfigurations
  - mutatingwebhookconfigurations
  verbs:
  - get
  - watch
  - list
  - update
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
