apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: defaulting.webhook.controlplane.kit.sh
webhooks:
- admissionReviewVersions: ["v1"]
  clientConfig:
    service:
      name: kit-webhook
      namespace: kit
  failurePolicy: Fail
  sideEffects: None
  name: defaulting.webhook.controlplane.kit.sh
  rules:
  - apiGroups:
    - kit.k8s.amazonaws.com
    apiVersions:
    - v1alpha1
    resources:
    - controlplanes
      controlplanes/status
    operations:
    - CREATE
    - UPDATE
    - DELETE

---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validation.webhook.controlplane.kit.sh
webhooks:
- admissionReviewVersions: ["v1"]
  clientConfig:
    service:
      name: kit-webhook
      namespace: kit
  failurePolicy: Fail
  sideEffects: None
  name: validation.webhook.controlplane.kit.sh
  rules:
  - apiGroups:
    - kit.k8s.amazonaws.com
    apiVersions:
    - v1alpha1
    resources:
    - controlplanes
      controlplanes/status
    operations:
    - CREATE
    - UPDATE
    - DELETE
