# See https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates#package-ecosystem
version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "monthly"
    ignore:
      - dependency-name: "k8s.io/api"
      - dependency-name: "k8s.io/apimachinery"
      - dependency-name: "k8s.io/client-go"
      - dependency-name: "sigs.k8s.io/controller-runtime"
      - dependency-name: "github.com/containerd/containerd"
      - dependency-name: "github.com/google/ko"
  - package-ecosystem: "github-actions"
    directory: "/.github"
    schedule:
      interval: "monthly"