apiVersion: v1
kind: Namespace
metadata:
  name: node-problem-detector
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: node-problem-detector
  namespace: node-problem-detector
spec:
  interval: 5m0s
  url: https://charts.deliveryhero.io/
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmChart
metadata:
  name: node-problem-detector
  namespace: node-problem-detector
spec:
  interval: 5m0s
  chart: node-problem-detector
  reconcileStrategy: ChartVersion
  sourceRef:
    kind: HelmRepository
    name: node-problem-detector
  version: '2.*'
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: node-problem-detector
  namespace: node-problem-detector
spec:
  interval: 2m
  targetNamespace: node-problem-detector
  chart:
    spec:
      chart: node-problem-detector
      sourceRef:
        kind: HelmRepository
        name: node-problem-detector
        namespace: node-problem-detector
      interval: 1m
  upgrade:
    remediation:
      remediateLastFailure: true
  values:
    tolerations:
    - key: CriticalAddonsOnly
      operator: Exists
      
    