apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata: 
  name: kit
spec:
  amiFamily: AL2
  subnetSelector:
    kit.sh/stack: KITInfrastructure
    aws-cdk:subnet-type: Private
  securityGroupSelector:
    kit.sh/stack: KITInfrastructure
---
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata: 
  name: kit
spec: 
  requirements: 
  - key: karpenter.sh/capacity-type
    operator: In
    values: 
      - on-demand
  - key: kubernetes.io/arch
    operator: In
    values:
      - amd64
  - key: kit.k8s.sh/app
    operator: Exists
  - key: "karpenter.k8s.aws/instance-cpu"
    operator: In
    values: ["16", "32", "48", "64"]
  - key: kit.k8s.sh/control-plane-name
    operator: Exists
  limits: 
    resources: 
      cpu: 1000
      memory: 1000Gi
  providerRef: 
      name: default
  ttlSecondsAfterEmpty: 300
