apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata: 
  name: default
spec:
  amiFamily: AL2
  subnetSelector:
    kit.sh/stack: KITInfrastructure
    aws-cdk:subnet-type: Private
  securityGroupSelector:
    kit.sh/stack: KITInfrastructure
  blockDeviceMappings:
  - deviceName: /dev/xvda
    ebs:
      volumeSize: 100Gi
      volumeType: gp3
---
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata: 
  name: default
spec: 
  requirements: 
  - key: karpenter.sh/capacity-type
    operator: In
    values: 
      - on-demand
  - key: kubernetes.io/arch
    operator: In
    values:
      - amd64
  - key: "karpenter.k8s.aws/instance-cpu"
    operator: In
    values: ["16", "32", "48", "64"]
  limits: 
    resources: 
      cpu: 8000
      memory: 2000Gi
  providerRef: 
      name: default
  ttlSecondsAfterEmpty: 864000
