apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kit-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kit-controller
subjects:
- kind: ServiceAccount
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kit-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kit-controller
subjects:
- kind: ServiceAccount
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kit-controller
rules:
- apiGroups: [kit.k8s.sh]
  resources: [controlplanes, controlplanes/status, dataplanes, dataplanes/status]
  verbs: [create, delete, get, list, patch, update, watch]
- apiGroups: [coordination.k8s.io]
  resources: [leases]
  verbs: [create, get, patch, update, watch]
- apiGroups: [""]
  resources: [configmaps, nodes, secrets, services, statefulsets, persistentvolumeclaims]
  verbs: [create, get, list, patch, update, watch]
- apiGroups: [apps]
  resources: [statefulsets, deployments, daemonsets]
  verbs: [create, get, list, patch, update, watch]
- apiGroups: [""]
  resources: [events]
  verbs: [create]
- apiGroups: ["monitoring.coreos.com"]
  resources: [podmonitors]
  verbs: [create, get, list, patch, update, watch]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kit-controller
rules:
- apiGroups: [""]
  resources: [configmaps]
  verbs: [create, get, list, patch, update, watch, delete]
- apiGroups: [""]
  resources: [configmaps/status]
  verbs: [get, patch, update]
