kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: kit-io1
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
parameters:
  type: "io1"
  iopsPerGB: "50"
reclaimPolicy: Delete
