apiVersion: v1
kind: ServiceAccount
metadata:
  name: kit-controller
  namespace: kit
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kit-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kit-controller
subjects:
- kind: ServiceAccount
  name: kit-controller
  namespace: kit
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kit-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kit-controller
subjects:
- kind: ServiceAccount
  name: kit-controller
  namespace: kit
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kit-controller
rules:
- apiGroups:
  - kit.k8s.amazonaws.com
  resources:
  - controlplanes
  - controlplanes/status
  verbs:
  - create
  - delete
  - patch
  - get
  - list
  - patch
  - watch
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - get
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  - services
  - statefulsets
  verbs:
  - get
  - create
  - update
  - patch
  - list
  - watch
- apiGroups:
  - "apps"
  resources:
  - statefulsets
  verbs:
  - get
  - create
  - update
  - list
  - watch
  - patch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kit-controller
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - configmaps/status
  verbs:
  - get
  - update
  - patch