apiVersion: kit.k8s.sh/v1alpha1
kind: ControlPlane
metadata:
  name: guest # Desired Cluster Name
spec:
  kubernetesVersion: "1.21"
  etcd:
    storageSpec:
      storageClassName: "ebs-sc"
      size: "40Gi"
  master:
    apiServer:
      spec:
        nodeSelector: 
          node.kubernetes.io/instance-type: m5.24xlarge
        containers: 
        - name: apiserver
          args: 
            - --max-requests-inflight=500
            - --max-mutating-requests-inflight=300
    controllerManager:
      spec:
        containers:
        - name: controller-manager
          args:
            - --kube-api-qps=50
    scheduler:
      spec:
        containers:
        - name: scheduler
          args:
            - --kube-api-qps=50
