apiVersion: kit.k8s.sh/v1alpha1
kind: DataPlane
metadata:
  name: example-nodes 
spec: 
  clusterName: example # Desired Cluster Name
  nodeCount: 1
  subnetSelector:
    kubernetes.io/cluster/kit-management-cluster: "*"
  instanceTypes:
    - c4.xlarge
    - c5.xlarge
    - c4.4xlarge
    - c5.4xlarge