# Steps to create a cluster with etcd running on mixed instances

## Create hollow pods to pre-provision mixed instances for etcd pods
```bash
ZONES=("a" "b" "c")
SIZES=("m5.large" "t3.medium" "c5.2xlarge")
CONTROL_PLANE=foo 
for i in {1..3}; do
cat <<EOF | kubectl apply -f -
  apiVersion: v1
  kind: Pod
  metadata:
    name: example-$i
    labels:
      node: control-plane
  spec:
    nodeSelector:
      kit.k8s.sh/app: etcd
      kit.k8s.sh/control-plane-name: $CONTROL_PLANE
      node.kubernetes.io/instance-type: ${SIZES[$i]}
      topology.kubernetes.io/zone: us-west-2${ZONES[$i]}
    containers:
      - name: inflate
        image: public.ecr.aws/eks-distro/kubernetes/pause:3.2
EOF
done
```

## Provision kubernetes cluster
```bash
CONTROL_PLANE=foo
cat <<EOF | kubectl apply -f -
apiVersion: kit.k8s.sh/v1alpha1
kind: ControlPlane
metadata:
  name: $CONTROL_PLANE # Desired Cluster Name
spec:
  etcd:
    replicas: 3
    spec:
      nodeSelector: 
        node.kubernetes.io/instance-type: ""
      containers: 
      - name: etcd
        args:
  master:
    apiServer:
      replicas: 1
EOF
```