# Steps to create a cluster with etcd running on mixed instances

## Create hollow pods to pre-provision mixed instances for etcd pods
```bash
ZONES=("a" "b" "c")
SIZES=("t3.medium" "t3.medium" "t2.medium")
CONTROL_PLANE=foo
for i in {1..3}; do
cat <<EOF | kubectl apply -f -
  apiVersion: v1
  kind: Pod
  metadata:
    name: example-$i
    labels:
      node: control-plane
  spec:
    nodeSelector:
      kit.k8s.sh/app: etcd
      kit.k8s.sh/control-plane-name: $CONTROL_PLANE
      node.kubernetes.io/instance-type: ${SIZES[$i]}
      topology.kubernetes.io/zone: us-west-2${ZONES[$i]}
    containers:
      - name: inflate
        image: public.ecr.aws/eks-distro/kubernetes/pause:3.2
EOF
done
```

## Provision kubernetes cluster
```bash
CONTROL_PLANE=foo # Desired Cluster name
cat <<EOF | kubectl apply -f -
apiVersion: kit.k8s.sh/v1alpha1
kind: ControlPlane
metadata:
  name: ${CONTROL_PLANE} # Desired Cluster name
spec:
  kubernetesVersion: "1.21"
  master:
    apiServer:
      replicas: 2
      spec:
        containers:
        - name: apiserver
          args:
            - --max-requests-inflight=400
            - --max-mutating-requests-inflight=200
    controllerManager:
      spec:
        containers:
        - name: controller-manager
          args:
            - --controllers=*
            - --kube-api-qps=300
            - --kube-api-burst=400
    scheduler:
      spec:
        containers:
        - name: scheduler
          args:
            - --kube-api-qps=300
            - --kube-api-burst=400
  etcd:
    spec:
      containers:
      - name: etcd
        resources:
          requests:
            memory: 2Gi
EOF
```

# Create Dataplane nodes for the guest cluster provisioned
```bash
CONTROL_PLANE=foo
cat <<EOF | kubectl apply -f -
apiVersion: kit.k8s.sh/v1alpha1
kind: DataPlane
metadata:
  name: ${CONTROL_PLANE}-nodes
spec:
  clusterName: ${CONTROL_PLANE} # Desired Cluster Name
  nodeCount: 10
  subnetSelector:
    kit.aws/substrate: ${MANAGEMENT_CLUSTER_NAME}
  instanceTypes:
    - c4.xlarge
    - c5.xlarge
    - c4.4xlarge
    - c5.4xlarge
EOF
```