apiVersion: v1
kind: Namespace
metadata:
  name: aws-node-termination-handler
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: eks-charts
  namespace: aws-node-termination-handler
spec:
  interval: 5m0s
  url: https://aws.github.io/eks-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nth
  namespace: aws-node-termination-handler
spec:
  interval: 2m
  targetNamespace: aws-node-termination-handler
  chart:
    spec:
      chart: aws-node-termination-handler
      sourceRef:
        kind: HelmRepository
        name: eks-charts
        namespace: aws-node-termination-handler
      interval: 1m
  upgrade:
    remediation:
      remediateLastFailure: true
  values:
    tolerations:
    - key: CriticalAddonsOnly
      operator: Exists
    enableSpotInterruptionDraining: true
    enableRebalanceMonitoring: true
    enableRebalanceDraining: false
    enableScheduledEventDraining: true
      
    