AWSTemplateFormatVersion: "2010-09-09"
Description: Resources used by https://github.com/awslabs/kubernetes-iteration-toolkit/operator
Parameters:
  ClusterName:
    Type: String
    Description: "Substrate/host cluster name"
Resources:
  KitControllerPolicy:
    Type: "AWS::IAM::ManagedPolicy"
    Properties:
      ManagedPolicyName: !Sub "KitControllerPolicy-${ClusterName}"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Resource: "*"
            Action:
              # Write Operations
              - "ec2:CreateTags"
              - "ec2:CreateLaunchTemplate"
              - "ec2:CreateLaunchTemplateVersion"
              - "ec2:DeleteLaunchTemplate"
              - "ec2:RunInstances"
              - "iam:passRole"
              - "autoscaling:CreateOrUpdateTags"
              - "autoscaling:CreateAutoScalingGroup"
              - "autoscaling:DeleteAutoScalingGroup"
              - "autoscaling:UpdateAutoScalingGroup"
              - "autoscaling:SetDesiredCapacity"
              - "iam:CreateRole"
              - "iam:AddRoleToInstanceProfile"
              - "iam:CreateInstanceProfile"
              - "iam:AttachRolePolicy"
              - "iam:RemoveRoleFromInstanceProfile"
              - "iam:DeleteInstanceProfile"
              - "iam:DetachRolePolicy"
              - "iam:DeleteRole"
              - "iam:TagRole"
              # Read Operations
              - "ec2:DescribeInstances"
              - "ec2:DescribeLaunchTemplates"
              - "ec2:DescribeLaunchTemplateVersions"
              - "ec2:DescribeSubnets"
              - "ssm:GetParameter"
              - "autoscaling:DescribeAutoScalingGroups"
              - "iam:GetRole"
              - "iam:GetInstanceProfile"
