AWSTemplateFormatVersion: "2010-09-09"
Description: Resources used by https://github.com/awslabs/kit/operator
Parameters:
  OpenIDConnectIdentityProvider:
    Type: String
    Description: "Example oidc.eks.us-west-2.amazonaws.com/id/1234567890"
  ClusterName:
    Type: String
    Description: "EKS cluster name"
Resources:
  KitControllerRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: "KITControllerRole"
      Path: /
      AssumeRolePolicyDocument: !Sub |
        {
          "Version": "2012-10-17",
          "Statement": [{
            "Effect": "Allow",
            "Principal": {
              "Federated": "arn:aws:iam::${AWS::AccountId}:oidc-provider/${OpenIDConnectIdentityProvider}"
            },
            "Action": "sts:AssumeRoleWithWebIdentity",
            "Condition": {
              "StringEquals": {
                "${OpenIDConnectIdentityProvider}:aud": "sts.${AWS::URLSuffix}",
                "${OpenIDConnectIdentityProvider}:sub": "system:serviceaccount:kit:kit"
              }
            }
          }]
        }
  KitControllerPolicy:
    Type: "AWS::IAM::Policy"
    Properties:
      PolicyName: "KitControllerPolicy"
      Roles:
        -
          Ref: "KitControllerRole"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Resource: "*"
            Action:
              # Write Operations
              - "ec2:CreateVpc"
              - "ec2:CreateSubnet"
              - "ec2:DeleteVpc"
              - "ec2:DeleteSubnet"
              - "ec2:CreateTags"
              - "iam:PassRole"
              # Read Operations
              - "ec2:DescribeVpcs"
              - "ec2:DescribeSubnets"