apiVersion: apps/v1
kind: Deployment
metadata:
  name: perfdash
  namespace: perfdash
spec:
  template:
    spec:
      containers:
      - name: perfdash
        command:
          - /perfdash
          - --www=true
          - --dir=/www/
          - --address=0.0.0.0:8080
          - --builds=100
          - --force-builds
          - --mode=s3
          - --aws-region=us-west-2
          - --configPath=/etc/config/jobs.yaml
          - --logsBucket=$(PERFDASH_LOG_BUCKET)
          - --logsPath=
          - --storageURL=NotSupported
          - --allow-parsers-matching-all-tests=true
        env:
          - name: PERFDASH_LOG_BUCKET
            valueFrom:
              configMapKeyRef:
                name: perfdash-config
                key: PERFDASH_LOG_BUCKET
          - name: AWS_DEFAULT_REGION
            valueFrom:
              configMapKeyRef:
                name: perfdash-config
                key: AWS_DEFAULT_REGION
          - name: AWS_REGION
            valueFrom:
              configMapKeyRef:
                name: perfdash-config
                key: AWS_REGION
          - name: AWS_WEB_IDENTITY_TOKEN_FILE
            value: /var/run/secrets/eks.amazonaws.com/serviceaccount/token
        # remove the resource request since it requests a lot.
        resources: null
        volumeMounts:
          - name: config-volume
            mountPath: /etc/config
        livenessProbe:
          initialDelaySeconds: 300
          timeoutSeconds: 5
      serviceAccountName: perfdash-log-fetcher
      tolerations:
        - key: CriticalAddonsOnly
          operator: Exists
      volumes:
        - name: config-volume
          configMap:
            name: perfdash-config
