apiVersion: v1
kind: Namespace
metadata:
  name: fluent-bit
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: eks-charts
  namespace: fluent-bit
spec:
  interval: 5m0s
  url: https://aws.github.io/eks-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: fluent-bit
  namespace: fluent-bit
spec:
  interval: 2m
  targetNamespace: fluent-bit
  chart:
    spec:
      chart: aws-for-fluent-bit
      sourceRef:
        kind: HelmRepository
        name: eks-charts
        namespace: fluent-bit
      interval: 1m
  upgrade:
    remediation:
      remediateLastFailure: true
  values:
    tolerations:
    - key: CriticalAddonsOnly
      operator: Exists
    cloudWatch:
      region: us-east-2
      logRetentionDays: 90
    firehose:
      enabled: false
    kinesis:
      enabled: false
    elasticsearch:
      enabled: false

      
    