---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: pod-density
spec:
  description: "clusterloader2 pod density task to run various types of cl2 tests on a given cluster."
  params:
  - name: giturl
    description: "git url to clone the package"
    default: https://github.com/kubernetes/perf-tests.git
  - name: nodes-per-namespace
    description: "nodes per namespace to get created for load test "
  - name: pods-per-node
    description: "pod density"
  - name: nodes
    description: "number of dataplane nodes to run the load test against"
  workspaces:
  - name: source
  - name: config
  - name: results
  - name: secrets
    mountPath: /root/.aws
  steps:
  - name: git-clone      
    image: alpine/git
    workingDir: $(workspaces.source.path)
    args: ["clone", "$(params.giturl)"]
  - name: prepare-loadtest
    image: amazon/aws-cli
    workingDir: $(workspaces.source.path)
    script: |
      cat > "$(workspaces.source.path)/overrides.yaml" <<EOL
      NODES_PER_NAMESPACE: $(params.nodes-per-namespace)
      PODS_PER_NODE: $(params.pods-per-node)
      ENABLE_SYSTEM_POD_METRICS: false
      NODE_MODE: master 
      EOL
  - name: validate-cluster
    image: amazon/aws-cli
    workingDir: $(workspaces.source.path)
    script: |
      mkdir -p /root/.kube/
      cp $(workspaces.config.path)/kubeconfig /root/.kube/config
      # TODO: Move to a separate task and chain it to this task through pipeline if we need more checks than just these before kicking off test.
      #kubectl commands are purely for knowing state of cluster before kicking off the test.
      curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
      install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
      kubectl version
      kubectl config current-context
      kubectl get nodes 
      kubectl get ns
      # end
  - name: run-loadtest
    image: 197575167141.dkr.ecr.us-west-2.amazonaws.com/clusterloader2:76e3fd7
    command: ["./clusterloader"]
    args: 
    - --kubeconfig=$(workspaces.config.path)/kubeconfig
    - --testconfig=$(workspaces.source.path)/perf-tests/clusterloader2/testing/density/config.yaml
    - --testoverrides=$(workspaces.source.path)/overrides.yaml
    - --nodes=$(params.nodes) 
    - --provider=eks 
    - --report-dir=$(workspaces.results.path)
    - --alsologtostderr
    env:
    - name: ENABLE_EXEC_SERVICE
      value: "false"
