name: Build and test CDK module
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  workflow_dispatch: {}
jobs:
  cdk-ci:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest]
        node-version: [14, 16]
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Build and test NPM packages
      run: |
        cd infrastructure/
        npm ci
        npm run build
        # TODO: enable it when we have at least one test.
        # npm test 
