
name: Build the operator image and push to public ECR on the main branch
on:
  push:
    branches: [main]
jobs:
  build-push-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
            ~/go/bin/
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Build & Test
        run: |
          echo "/usr/local/kubebuilder/bin" >> $GITHUB_PATH
          make toolchain build test
        working-directory: operator
      - uses: docker/login-action@v1
        with:
          registry: public.ecr.aws
          username: ${{ secrets.AWS_ACCESS_KEY_ID }}
          password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        env:
          AWS_REGION: us-east-1
      - name: Install KO binary
        run: |
          VERSION=0.8.3
          OS=Linux
          ARCH=x86_64
          curl -L https://github.com/google/ko/releases/download/v${VERSION}/ko_${VERSION}_${OS}_${ARCH}.tar.gz | tar xzf - ko
          chmod +x ./ko
          mv ko ~/go/bin/
      - name: Push to ECR public
        run: |
          KO_DOCKER_REPO=public.ecr.aws/i7d3g4r4/kit-operator ko publish --bare ./cmd/controller
        working-directory: operator
