name: Second Workflow
on:
  workflow_run:
    types: [completed]
    workflows: [First]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
     - name: Print message
       run: echo "Second workflow starting"